DROP TABLE IF EXISTS game;

CREATE TABLE game (
  id SERIAL PRIMARY KEY,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  turn INTEGER NOT NULL DEFAULT 0,
  owner TEXT NOT NULL,
  players TEXT[] DEFAULT '{}'::text[]
)