DROP TABLE IF EXISTS figure;
DROP TABLE IF EXISTS game_user;
DROP TABLE IF EXISTS game;

CREATE TABLE game_user (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE figure (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  figure_name TEXT NOT NULL,
  strength INTEGER NOT NULL,
  dexterity INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES game_user (id)
);

CREATE TABLE game (
  id SERIAL PRIMARY KEY,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  turn INTEGER NOT NULL DEFAULT 0,
  owner TEXT NOT NULL,
  players TEXT[] DEFAULT '{}'::text[]
)